# Generated by Django 3.0.3 on 2020-08-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Emp_management', '0005_auto_20200823_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
